# Generated by Django 4.0.6 on 2022-08-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('importance', models.CharField(max_length=50)),
                ('review', models.IntegerField(choices=[(1, 'Good'), (2, 'Better'), (3, 'Favorite')])),
            ],
        ),
    ]
